#
# © JSC NICEVT
#
---
- hosts: virt-nodes
  user: root

  tasks:
   - name: обновление списка пакетов
     apt: update_cache=yes

   - name: устанавливаем пакет ocfs2
     apt: pkg=ocfs2-tools state=present 

   - name: настраиваем файл /etc/default/o2cb -- включаем параметр O2CB_ENABLED
     lineinfile: dest=/etc/default/o2cb regexp='O2CB_ENABLED=' line='O2CB_ENABLED=true' state=present

   - name: создание файла /etc/ocfs2/cluster.conf
     template: owner=root group=root mode=644
        src=cluster.conf.j2 dest=/etc/ocfs2/cluster.conf

   - name: активируем службу ocfs2
     systemd:
       name: ocfs2
       state: started
       enabled: yes

   - name: регистриурем кластер ocfs2
     shell: o2cb register-cluster ocfs2

#   - name: активируем службу ocfs2
#     shell: systemctl enable ocfs2
#
#   - name: запускаем службу lvm2-monitor
#     shell: systemctl start lvm2-monitor
#
- hosts: virt-node-1.sandbox.era.mil.ru
  user: root

  tasks:
#   - name: создаем файловую систему ocfs2 на разделе /dev/vg-one-test/lvm_images
#     filesystem:
#       fstype: ocfs2
#       dev: /dev/vge-one-test/lvm_images

   - name: создаем файловую систему ocfs2 на разделе /dev/vg-one-test/lvm_images
     shell: mkfs.ocfs2 /dev/vg-one-test/lvm_images
