---
# - debug: var=hostvars[inventory_hostname]

 - file: path={{ repos.path }}/tftpboot state=directory owner=dnsmasq mode=0755

 - name: делаем шаблон
   template: dest={{ repos.path }}/tftpboot/{{ preseed.name }} src=era-preseed
             owner=dnsmasq mode=0644
